#---------------------------------#
#      general configuration      #
#---------------------------------#

version: '1.0.1.{build}'

branches:
  only:
    - master

#---------------------------------#
#    environment configuration    #
#---------------------------------#

image:
- Visual Studio 2017

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

#---------------------------------#
#       build configuration       #
#---------------------------------#

platform:
  - Any CPU

configuration:
  - Release

before_build:
  - nuget restore

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test:
  assemblies:
    only:
      - '**\*.Tests.dll'

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: '**\*.nupkg'

#---------------------------------#
#     deployment configuration    #
#---------------------------------#
deploy:
  - provider: NuGet
    api_key:
      secure: b//n09LbYqcXFpWP5P27VoycalLwhxQ295Obl/bED9qOnI+iRtxRTA7O6y0BRmYt
    skip_symbols: true
    artifact: /.*\.nupkg/
#    on:
#      APPVEYOR_REPO_TAG: true
