#---------------------------------#
#      general configuration      #
#---------------------------------#

version: '1.0.{build}'

branches:
  only:
    - master

#---------------------------------#
#    environment configuration    #
#---------------------------------#

image:
- Visual Studio 2017

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

#---------------------------------#
#       build configuration       #
#---------------------------------#

platform:
  - Any CPU

configuration:
  - Release

before_build:
  - nuget restore

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test:
  assemblies:
    only:
      - '**\*.Tests.dll'
      
#---------------------------------#
#     deployment configuration    #
#---------------------------------#

