#---------------------------------#
#      general configuration      #
#---------------------------------#

# version: '1.0.0.{build}'

branches:
  only:
    - master

install:
  - choco install gitversion.portable -pre -y

assembly_info:
  patch: false

#---------------------------------#
#    environment configuration    #
#---------------------------------#

image:
- Visual Studio 2017

#dotnet_csproj:
#  patch: true
#  file: '**\*.csproj'
#  version: '{version}'
#  package_version: '{version}'
#  assembly_version: '{version}'
#  file_version: '{version}'
#  informational_version: '{version}'

#---------------------------------#
#       build configuration       #
#---------------------------------#

platform:
  - Any CPU

configuration:
  - Release

before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

build:
  project: FastActivator.sln

after_build:
  - cmd: ECHO nuget pack GriffinPlus.Lib.FastActivator\obj\%CONFIGURATION%\GriffinPlus.Lib.FastActivator.1.0.0.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
  - cmd: nuget pack GriffinPlus.Lib.FastActivator\obj\%CONFIGURATION%\GriffinPlus.Lib.FastActivator.1.0.0.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
  - cmd: appveyor PushArtifact "GriffinPlus.Lib.FastActivator.%GitVersion_NuGetVersion%.nupkg"

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test:
  assemblies:
    only:
      - '**\*.Tests.dll'

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: '*\*.nupkg'

#---------------------------------#
#     deployment configuration    #
#---------------------------------#
deploy:
  - provider: NuGet
    api_key:
      secure: b//n09LbYqcXFpWP5P27VoycalLwhxQ295Obl/bED9qOnI+iRtxRTA7O6y0BRmYt
    skip_symbols: true
    artifact: /.*\.nupkg/
#    on:
#      APPVEYOR_REPO_TAG: true
