#---------------------------------#
#      general configuration      #
#---------------------------------#

branches:
  only:
    - master

install:
  - git submodule update --init --recursive

#---------------------------------#
#    environment configuration    #
#---------------------------------#

image:
- Visual Studio 2017

#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
  - powershell -file Build.ps1 -buildserver

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test_script:
  - vstest.console "_build\FastActivator.AnyCPU.Release\netcoreapp2.0\GriffinPlus.Lib.FastActivator.Tests.dll"

#---------------------------------#
#      packaging artifacts        #
#---------------------------------#

artifacts:
  - path: '**\*.nupkg'

#---------------------------------#
#     deployment configuration    #
#---------------------------------#
deploy:
  - provider: NuGet
    api_key:
      secure: OkWXkTuGyjQQ5m5jQ2aI1ant3mAtLYCE0n6zAqHDpFwLUvPMH9eRMSyI1YXsz9+1
    skip_symbols: true
    artifact: /.*\.nupkg/
    on:
      APPVEYOR_REPO_TAG: true
