#######################################################################################################################
# build.vs: ci-csharp-netstandard20-with-deployment-on-tag.yml
#######################################################################################################################
#
# The pipeline runs unit tests on the following target frameworks and platforms:
#
# - Windows Server 2022, .NET 4.6.1      (tests with build for .NET Framework 4.6.1)
# - Windows Server 2022, .NET Core 2.2   (tests with build for .NET Standard 2.0)
# - Windows Server 2022, .NET Core 3.1   (tests with build for .NET Standard 2.1)
# - Windows Server 2022, .NET 5.0        (tests with build for .NET 5)
# - Windows Server 2022, .NET 6.0        (tests with build for .NET 6)
# - Windows Server 2022, .NET 7.0        (tests with build for .NET 6)
# - Ubuntu 22.04, .NET Core 2.2          (tests with build for .NET Standard 2.0)
# - Ubuntu 22.04, .NET Core 3.1          (tests with build for .NET Standard 2.1)
# - Ubuntu 22.04, .NET 5.0               (tests with build for .NET 5)
# - Ubuntu 22.04, .NET 6.0               (tests with build for .NET 6)
# - Ubuntu 22.04, .NET 7.0               (tests with build for .NET 6)
#
# After tests have completed successfully nuget packages are created according to their specification (*.nuspec).
# If the build was tagged with a tag starting with 'v' the nuget packages are pushed to nuget.org.
#
#######################################################################################################################

trigger:
  tags:
    include:
    - v*
  branches:
    include:
    - master

pool:
  vmImage: 'windows-2022'

stages:

########################################################################################################################
# Stage: Build
########################################################################################################################
- stage: 'Build'
  jobs:
  ######################################################################################################################
  # Job: Build
  ######################################################################################################################
  - job: 'Build'
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core 2.2 SDK'
      inputs:
        packageType: 'sdk'
        version: '2.2.x'
        installationPath: '$(Agent.ToolsDirectory)/dotnet'
    - task: UseDotNet@2
      displayName: 'Use .NET Core 3.1 SDK'
      inputs:
        packageType: 'sdk'
        version: '3.1.x'
        installationPath: '$(Agent.ToolsDirectory)/dotnet'
    - task: UseDotNet@2
      displayName: 'Use .NET 5.0 SDK'
      inputs:
        packageType: 'sdk'
        version: '5.0.x'
        installationPath: '$(Agent.ToolsDirectory)/dotnet'
    - task: UseDotNet@2
      displayName: 'Use .NET 6.0 SDK'
      inputs:
        packageType: 'sdk'
        version: '6.0.x'
        installationPath: '$(Agent.ToolsDirectory)/dotnet'
    - task: UseDotNet@2
      displayName: 'Use .NET 7.0 SDK'
      inputs:
        packageType: 'sdk'
        version: '7.0.x'
        installationPath: '$(Agent.ToolsDirectory)/dotnet'
    - task: DotNetCoreCLI@2
      displayName: 'Install GitVersion'
      inputs:
        command: 'custom'
        custom: 'tool'
        arguments: 'install -g gitversion.tool'
    - task: DotNetCoreCLI@2
      displayName: 'Show GitVersion Version'
      inputs:
        command: 'custom'
        custom: 'gitversion'
        arguments: 'version'
    - task: DotNetCoreCLI@2
      name: 'GitVersion'
      displayName: 'Run GitVersion'
      inputs:
        command: 'custom'
        custom: 'gitversion'
        arguments: '/output buildserver /updateassemblyinfo src/CommonAssemblyInfo.cs'
    - task: DotNetCoreCLI@2
      displayName: 'Restore'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
    - task: DotNetCoreCLI@2
      displayName: 'Build'
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '/p:InformationalVersion=$(GitVersion.InformationalVersion)'
        versioningScheme: 'byEnvVar'
        versionEnvVar: 'GitVersion.SemVer'
    - task: PowerShell@2
      displayName: 'Export Shared Variables'
      inputs:
        targetType: 'inline'
        pwsh: true
        script: |
          New-Item -ItemType Directory -Force -Path '$(Pipeline.Workspace)/variables'
          Set-Location -Path '$(Pipeline.Workspace)/variables'
          '$(GitVersion.NuGetVersion)' | Out-File GitVersion.NuGetVersion -NoNewLine
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Pipeline Artifacts'
      inputs:
        targetPath: '$(Build.SourcesDirectory)/_build'
        artifactName: 'Binaries'
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Shared Variables'
      inputs:
        targetPath: '$(Pipeline.Workspace)/variables'
        artifactName: 'Variables'

########################################################################################################################
# Stage: Tests
########################################################################################################################
- stage: 'Tests'
  jobs:
  ######################################################################################################################
  # Job:
  # - .NET Framework 4.6.1 on Windows Server 2022
  # - .NET Core 2.2 on Windows Server 2022 and Ubuntu 22.04
  # - .NET Core 3.1 on Windows Server 2022 and Ubuntu 22.04
  # - .NET 5.0 on Windows Server 2022 and Ubuntu 22.04
  # - .NET 6.0 on Windows Server 2022 and Ubuntu 22.04
  # - .NET 7.0 on Windows Server 2022 and Ubuntu 22.04
  ######################################################################################################################
  - job:
    displayName: ''
    timeoutInMinutes: 120
    strategy:
      matrix:
        'Windows Server 2022':
          VmImage: 'windows-2022'
        'Ubuntu 22.04':
          VmImage: 'ubuntu-22.04'
    pool:
      vmImage: '$(VmImage)'
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core 2.2 SDK'
      inputs:
        packageType: 'sdk'
        version: '2.2.x'
        installationPath: '$(Agent.ToolsDirectory)/dotnet'
    - task: UseDotNet@2
      displayName: 'Use .NET Core 3.1 SDK'
      inputs:
        packageType: 'sdk'
        version: '3.1.x'
        installationPath: '$(Agent.ToolsDirectory)/dotnet'
    - task: UseDotNet@2
      displayName: 'Use .NET 5.0 SDK'
      inputs:
        packageType: 'sdk'
        version: '5.0.x'
        installationPath: '$(Agent.ToolsDirectory)/dotnet'
    - task: UseDotNet@2
      displayName: 'Use .NET 6.0 SDK'
      inputs:
        packageType: 'sdk'
        version: '6.0.x'
        installationPath: '$(Agent.ToolsDirectory)/dotnet'
    - task: UseDotNet@2
      displayName: 'Use .NET 7.0 SDK'
      inputs:
        packageType: 'sdk'
        version: '7.0.x'
        installationPath: '$(Agent.ToolsDirectory)/dotnet'
    - task: DownloadPipelineArtifact@2
      displayName: 'Download Pipeline Artifacts'
      inputs:
        artifact: 'Binaries'
        targetPath: '$(Build.SourcesDirectory)/_build'
    - task: DotNetCoreCLI@2
      displayName: 'Test .NET Framework 4.6.1'
      condition: eq(variables['agent.os'], 'Windows_NT')
      inputs:
        command: 'test'
        projects: '**/*Tests/*.csproj'
        nobuild: true
        arguments: '--framework net461 --verbosity normal'
    - task: DotNetCoreCLI@2
      displayName: 'Test .NET Core 2.2'
      inputs:
        command: 'test'
        projects: '**/*Tests/*.csproj'
        nobuild: true
        arguments: '--framework netcoreapp2.2'
    - task: DotNetCoreCLI@2
      displayName: 'Test .NET Core 3.1'
      inputs:
        command: 'test'
        projects: '**/*Tests/*.csproj'
        nobuild: true
        arguments: '--framework netcoreapp3.1'
    - task: DotNetCoreCLI@2
      displayName: 'Test .NET 5.0'
      inputs:
        command: 'test'
        projects: '**/*Tests/*.csproj'
        nobuild: true
        arguments: '--framework net5.0'
    - task: DotNetCoreCLI@2
      displayName: 'Test .NET 6.0'
      inputs:
        command: 'test'
        projects: '**/*Tests/*.csproj'
        nobuild: true
        arguments: '--framework net6.0'
    - task: DotNetCoreCLI@2
      displayName: 'Test .NET 7.0'
      inputs:
        command: 'test'
        projects: '**/*Tests/*.csproj'
        nobuild: true
        arguments: '--framework net7.0'

########################################################################################################################
# Stage: Deployment
########################################################################################################################
- stage: 'Deployment'
  jobs:
  ######################################################################################################################
  # Job: Pack
  ######################################################################################################################
  - job: 'Pack'
    steps:
    - task: DownloadPipelineArtifact@2
      displayName: 'Download Pipeline Artifacts'
      inputs:
        artifact: 'Binaries'
        targetPath: '$(Build.SourcesDirectory)/_build'
    - task: DownloadPipelineArtifact@2
      displayName: 'Download Pipeline Artifacts'
      inputs:
        artifact: 'Variables'
        targetPath: '$(Pipeline.Workspace)/variables'
    - task: PowerShell@2
      displayName: 'Import Shared Variables'
      inputs:
        targetType: 'inline'
        pwsh: true
        workingDirectory: '$(Pipeline.Workspace)/variables'
        script: |
          foreach ( $file in Get-ChildItem ) {
            $value = Get-Content $($file.FullName) -Raw
            Write-Host "Setting variable '$($file.Name)' = '$value'"
            Write-Host "##vso[task.setvariable variable=$($file.Name)]$value";
          }
    - task: PowerShell@2
      displayName: 'Pack'
      inputs:
        targetType: 'inline'
        pwsh: true
        script: |
          foreach ( $file in Get-ChildItem -Include *.nuspec -Recurse ) {
            Write-Host "Processing file $($file.FullName)..."
            nuget.exe pack `
              "$($file.FullName)" `
              -Symbols `
              -SymbolPackageFormat snupkg `
              -Properties version=$(GitVersion.NuGetVersion) `
              -OutputDirectory "$(Build.ArtifactStagingDirectory)" `
              -Verbosity detailed
            if ($lastexitcode -ne 0) { throw("Creating nuget package failed.") }
          }
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Pipeline Artifacts'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'Packages'

  ######################################################################################################################
  # Job: Publish
  ######################################################################################################################
  - job:
    displayName: 'Publish'
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/v')
    dependsOn: 'Pack'
    steps:
    - task: DownloadPipelineArtifact@2
      displayName: 'Download Pipeline Artifacts'
      inputs:
        artifact: 'Packages'
        targetPath: '$(Build.ArtifactStagingDirectory)'
    - task: NuGetCommand@2
      displayName: 'Publish'
      inputs:
        command: 'push'
        nuGetFeedType: 'external'
        publishFeedCredentials: 'nuget.org'
